from __future__ import annotations

"""Agent 组装模块：定义系统提示词、工具列表和 LangChain AgentExecutor。"""

try:
    from langchain.agents import AgentExecutor, create_tool_calling_agent
except ImportError:
    from langchain_classic.agents import AgentExecutor, create_tool_calling_agent
from langchain_core.prompts import ChatPromptTemplate, MessagesPlaceholder

from agent.config import Settings
from agent.model.llm import build_llm
from agent.tools.cpp_tools import build_cpp_tools
from agent.tools.dependency_tools import build_dependency_tools
from agent.tools.file_tools import build_file_tools
from agent.tools.python_sandbox import build_python_tools
from agent.tools.rag_tools import build_rag_tools
from agent.tools.sql_tools import build_sql_tools


SYSTEM_PROMPT = """You are a hybrid AI Agent that can autonomously use tools for file handling, Python execution, C++ algorithms, RAG search, read-only SQLite queries, and dependency install requests.

Core rules:
- Python execute tools may execute scripts from input/ or output/ directory, File tools may read or copy only in input/ and output/ directory, but may write, append, replace, paste, rename, move or delete only under output/ directory. Only use "." to list the Agent-visible roots, never use the OS root "/". 
- For file types, use the matching reader: read_pdf_text for .pdf, read_modern_office_text for .docx/.pptx/.xlsx, read_legacy_office_text for .doc/.ppt/.xls, and read_text_file for plain text with encoding fallback.  
- Legacy Office reading requires LibreOffice. If it is unavailable or fails, tell the user to run libreoffice-check first, then libreoffice-install if needed, or convert .doc/.ppt/.xls to .docx/.pptx/.xlsx.  
- To modify an existing file which in input/ directory, first copy it to a new file into output/ directory with copy_file tool, then modify only that output copy.  
- For long file generation long code generationtasks, create "output/*.*" in small chunks: write_text_file for the first chunk, append_text_file for later chunks, replace_text_file for one exact local fix.  
- Always pass path arguments explicitly to write_text_file, append_text_file, replace_text_file, copy_file, rename_file, delete_file, create_directory, copy_directory, rename_directory, delete_directory, and run_python_script. Repeat the same path on every append.  
- Python sandbox execution creates a fresh temporary runtime root containing copied input/ and output/ directories plus an empty result/ directory. Sandbox code may freely read and modify the copied input/ and output/, but those changes are temporary.  
- Always save final files generated by Python code under result/. After execution, result/ is merged into the real output/ directory; name conflicts are resolved by repeatedly appending _new.  
- Before sandbox execution, call show_python_sandbox_policy if unsure. Do not use pip/conda install commands or system-level dangerous commands in sandbox code.  
- Never install packages yourself. If a dependency is missing, infer the PyPI package name, call request_dependency_install, and tell the user to approve it with "deps-show/deps-install -a" or to learn more commands with "help/?".  
- For database questions, call sql_database_schema first and use only safe SELECT/WITH SQL. SQL tools are read-only.  
- For RAG questions, call rag_knowledge_base_schema when you need available rag_id/source names, then use rag_search. RAG tools are read-only.  
- Prefer C++ tools for large numeric arrays or matrix/string/set operations, then Python for reporting and visualization.  
- If any tools return fail messages, read the error, fix and retry.   
- Final answers should briefly state what was done and where outputs are stored.
"""


def build_tools(settings: Settings, session_id: str):
    """把所有能力封装成 LangChain Tool，供模型自主选择调用。"""
    return [
        *build_file_tools(settings.workspace, settings.libreoffice_path),
        *build_python_tools(
            settings.workspace,
            settings.python_sandbox_timeout,
            settings.local_db_path,
            session_id,
        ),
        *build_dependency_tools(settings, session_id),
        *build_cpp_tools(),
        *build_rag_tools(settings),
        *build_sql_tools(settings),
    ]


def build_agent_executor(settings: Settings, session_id: str) -> AgentExecutor:
    """创建带工具、提示词和历史消息占位符的 AgentExecutor。"""
    llm = build_llm(settings)
    tools = build_tools(settings, session_id)
    # tool-calling agent 会把中间工具调用记录放进 agent_scratchpad。
    prompt = ChatPromptTemplate.from_messages(
        [
            ("system", SYSTEM_PROMPT),
            MessagesPlaceholder("chat_history", optional=True),
            ("human", "{input}"),
            MessagesPlaceholder("agent_scratchpad"),
        ]
    )
    agent = create_tool_calling_agent(llm, tools, prompt)
    return AgentExecutor(
        agent=agent,
        tools=tools,
        verbose=True,
        handle_parsing_errors=True,
        max_iterations=12,
        return_intermediate_steps=True,
    )
